"""Initial migration.

Revision ID: 01a3dd016741
Revises: 
Create Date: 2024-08-08 16:35:31.518299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a3dd016741'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(length=500), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('bt', sa.String(length=10), nullable=False),
    sa.Column('co', sa.String(length=10), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('answer_key', sa.String(length=500), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    op.drop_table('question')
    # ### end Alembic commands ###
